include ../../Makefile

panelize: ## Save changes into repository automatically.
	@kikit panelize \
		--layout 'grid; rows: 1; cols: 3; space: 2mm' \
		--tabs 'fixed; width: 8mm; vcount: 0' \
		--cuts vcuts \
		--framing 'railslr; width: 5mm; space: 3mm;' \
		--post 'millradius: 1mm' USBC2.kicad_pcb panel.kicad_pcb
